version: "3.8"
services:
  userdb:
    image: mysql:8.0
    container_name: userdb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb
    ports:
      - "3306:3306"
    networks:
      - app-network

  user-service:
    build:
      context: .
      dockerfile: services/microservices-java/user-service/Dockerfile
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - userdb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge